name: Aether
version: ${project.version}
main: net.oriserver.aether.aether.Aether
load: POSTWORLD
softdepend: [Multiverse-Core]

commands:
  getphone:
    description: Ather Phone入手
    aliases:
      - gp
      - phone
      - getPhone
  saveteleport:
    description: 現在地を保存
    aliases:
      - st
      - SaveTeleport
  saveitem:
    description: 持っているアイテムを保存
    aliases:
      - SaveItem
      - si
  rename:
    description: 持っているアイテムの名前を変更

  chatroom:
    description: チャットルームのコマンド

  saveinventory:
    description: インベントリーを保存します
    aliases: sinv

  getfirstinv:
    description: FirstInventoryを設定する
    aliases:
      - fi
      - getFirstInventory
      - firstinv

  hide:
    description: Hide a specific player or all players
    usage: /<command> [playerName]
  show:
    description: Show a specific player or all players
    usage: /<command> [playerName]

  teleportaether:
    description: teleport
    usage: /<command> [level || chart] [number]
    aliases:
      - tpa
  i:
    description: 座標表示
  TNTRun:
    description: TNTRun setting
    usage: /<command> [create]
    aliases:
      - TNTrun
      - tntrun
      - TNTRun

  chart:
    description: chartStage
    usage: /<command> [create-rework] [stage_id]
    aliases:
      - chart
      - chartStage
      - ChartStage

  sound:
    description: play sound
    usage: /<command> [check-off]

  skull:
    description: skin入手

  particle:
    description: パーティクル

  createinventory:
    description: Inventory作成
    aliases:
      - cinv
      - createinv
      - CreateInventory

  savecommand:
    description: save command
    aliases:
      - sc
      - SaveCommand
  openphone:
    description: open phone
    aliases:
      - ap
      - openPhone
      - aetherphone